apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capactiy:
     storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssda
  nodeAffinity: 
    required: 
       nodeSelectorTerms:
       - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values: 
           - example-node


# NOTE: THEY ARE NOT NAMED SPACE
       